### ISSUE TITLE
Create a gitaction to update doc's search index

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/docs#1]
Right now the crawler runs form a VM on Adam's account.  We would like to move it to a Git action. Documentation on how to run it here: 

https://osmosis-labs.atlassian.net/wiki/spaces/OL/pages/295173/Algolia+Search

**Comment by czarcas7ic** [comment]
Completed, see https://github.com/osmosis-labs/docs/blob/main/.github/workflows/scrape.yml
