### ISSUE TITLE
Osmosis repository module spec location changes

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/docs#121]
## Summary

"Osmosis Core Development" module docs point to the `x/< module name >/spec/README.md` files for each module in the https://github.com/osmosis-labs/osmosis repository.

We are planning to move these files to a different location. This is an issue to track the change in the docs repo to make sure that the docs website is functional after the change.

The relevant issue in the osmosis repository: https://github.com/osmosis-labs/osmosis/issues/1864

**Comment by daniel-farina** [comment]
Fixed, thanks
