### ISSUE TITLE
Superfluid - typos

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/docs#140]
## Summary of Bug

Found some typos (there may be more):

https://docs.osmosis.zone/developing/osmosis-core/modules/spec-superfluid.html#syntheticlockups
"SyntheticLockups are **synthetica** of PeriodLocks" -> "SyntheticLockups are **synthetic forms** of PeriodLocks"

https://docs.osmosis.zone/developing/osmosis-core/modules/spec-superfluid.html#intermediary-account
"Intermediary Accounts **establishes** the connections" -> "Intermediary Accounts **establish** the connections"

https://docs.osmosis.zone/developing/osmosis-core/modules/spec-superfluid.html#superfluid-asset
"A superfluid asset is **a** alternative asset (non-OSMO)" -> "A superfluid asset is **an** alternative asset (non-OSMO)"

https://docs.osmosis.zone/developing/osmosis-core/modules/spec-superfluid.html#osmo-equivalent-multipliers
"The multiplier for OSMO is **alway** 1." -> "The multiplier for OSMO is **always** 1."

May be worth looking into a VSCode or browser extension for proofreading.

**Comment by daniel-farina** [comment]
Fixed, thanks
