### ISSUE TITLE
Wrong config file path for hermes config.tmol

### ISSUE THREAD

**Issue by iiimoon** [osmosis-labs/docs#155]
## Summary of Bug

in previous step the file is copied directly under .hermes  folder "cp config.toml $HOME/.hermes" 
but doing view using config directory path nano $HOME/.hermes/config/config.toml

## Steps to Reproduce

1. ...

----

**Comment by daniel-farina** [comment]
Thank you, so what is the correct path?

**Comment by daniel-farina** [comment]
I just saw your PR, I commited it here because he just refactored the docs:
https://github.com/osmosis-labs/docs/commit/fa3a79169136f9244da839966da0ceae48f80a3d

tysm
