### ISSUE TITLE
Update How to Add External Incentive Gauges onto the Osmosis Pools Page 

### ISSUE THREAD

**Issue by gnujoow** [osmosis-labs/docs#194]
## Summary

from the issue blow, external gauge is moved to nextjs server but the guide still guide old way
https://github.com/osmosis-labs/osmosis-frontend/issues/853
https://github.com/osmosis-labs/osmosis-frontend/issues/1182
https://github.com/osmosis-labs/osmosis-frontend/issues/1190

## Problem Definition

-

## Proposal

update https://github.com/osmosis-labs/docs/blob/main/docs/overview/integrate/frontend.md#steps-2 to deliver accurate information 

 

----

**Comment by daniel-farina** [comment]
@JeremyParish69

**Comment by JeremyParish69** [comment]
Thanks for this @gnujoow , you are correct this is outdated information and have started on working to update appropriately
