### ISSUE TITLE
Outdated commands for CLI

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/docs#209]
## Summary of Bug

There are lines of code are outdated and others that simply doesn't work as how they should. Examples:

This is one case:

<img width="825" alt="Untitled" src="https://github.com/osmosis-labs/docs/assets/61362029/a0b1c67f-4e5f-46f1-a097-4302d7033c41">

The command doesn't work. It's outdated

<img width="521" alt="image" src="https://github.com/osmosis-labs/docs/assets/61362029/200e581a-f67a-4f2f-80b4-720d8cc21531">

**Comment by daniel-farina** [comment]
merged, thanks!
