### ISSUE TITLE
incomplete QuickStart commands.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/docs#211]
## Summary of Bug

In `Osmosis CLI > Quick start` the commands are incomplete. You need to enter the folder to run `make build`.
<img width="835" alt="image" src="https://github.com/osmosis-labs/docs/assets/61362029/5ee9e14e-6871-4b57-9e02-a41b61ed12c4">

[Link](https://docs.osmosis.zone/osmosis-core/osmosisd)

**Comment by daniel-farina** [comment]
merged, thanks!
