### ISSUE TITLE
broken links in terminology.md

### ISSUE THREAD

**Issue by stevendavis** [osmosis-labs/docs#29]
This file:
overview/terminology.md

This text:
Osmosis’ design includes two mechanisms to incentivize long-term liquidity: exit fees and bonded liquidity gauges

The "exit fees" and "bonded liquidity gauges" links are not working.

Other than that, the glossary is well written and helpful.  Keep up the good work.

**Comment by daniel-farina** [comment]
Thank you, fixed.
