### ISSUE TITLE
Create documentation/guidelines for the release process

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/docs#4]
**Background**

We don't have any documentation/guidelines for releasing our projects. As a result, it takes a lot of time to onboard on that. We should have the sequence of steps and rules documented so that everyone is consistent and new contributors can understand the process quickly.

Relevant discussion on Slack: https://osmosis-network.slack.com/archives/C027ELA290B/p1643991656792299

**Acceptance Criteria**
- [ ] compile a document recommending a release process
- [ ] gather the team's feedback by asking for review and suggestions on Slack
- [ ] update the document

**Comment by r0mvn** [comment]
There are 2 problems currently present across our repositories:

1. It is hard to determine what is the latest stable released version

2. Difficult to determine what version of the SDK is used within Osmosis

**To be updated**
