### ISSUE TITLE
Scraper Github Action

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/docs#5]
I realized that the scraper github action runs too quickly after the main branch is updated and therefore doesn't index the changes properly unless it is manually rerun after the pages build and deployment is finished

**Comment by daniel-farina** [comment]
I added a simple fix to allow time for the site to be published and the cache from Github pages to be cleared. 
```
      - name: Sleep for 10 min to allow site to be published.
        run: sleep 10m

```
