### ISSUE TITLE
add umbrella section of "Getting Started" to guide newbies on how to contribute to Osmosis

### ISSUE THREAD

**Issue by jlbit** [osmosis-labs/docs#64]
Write a set of starter guidance for new developers to get up to speed quickly. The pain really comes from my experience with onboarding in past weeks that, as someone not so familiar with go/make, I had a super hard time to even build and run tests on osmosis codebase. 

cross referencing https://github.com/osmosis-labs/osmosis/issues/891 to here. We can include those suggestions (which is more in-depth than the starter kit) from @ValarDragon as well.

We can break down the effort into smaller one if needed.

**Comment by jblbit** [comment]
good documentation is likely the only (async) way to scale a global team efficiently
