### ISSUE TITLE
Some of the module sections point to invalid pages

### ISSUE THREAD

**Issue by george-aj** [osmosis-labs/docs#92]
https://docs.osmosis.zone/developing/osmosis-core/modules/spec-epochs.html
https://docs.osmosis.zone/developing/osmosis-core/modules/spec-gamm.html
https://docs.osmosis.zone/developing/osmosis-core/modules/spec-lockup.html
https://docs.osmosis.zone/developing/osmosis-core/modules/spec-mint.html
https://docs.osmosis.zone/developing/osmosis-core/modules/spec-incentives.html
https://docs.osmosis.zone/developing/osmosis-core/modules/spec-pool-incentives.html

**Comment by xBalbinus** [comment]
Ah! Fixing.

**Comment by xBalbinus** [comment]
It seems that the incentives needs to be fixed along with some other formatting issues with some of the other pages. Fixing.
